apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-voice-agent
  labels:
    app: react-voice-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-voice-agent
  template:
    metadata:
      labels:
        app: react-voice-agent
    spec:
      containers:
      - name: react-voice-agent
        image: ghcr.io/uengine-oss/react-voice-agent:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: SERVICE_ROLE_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-voice-agent-prod
  labels:
    app: react-voice-agent-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-voice-agent-prod
  template:
    metadata:
      labels:
        app: react-voice-agent-prod
    spec:
      containers:
      - name: react-voice-agent-prod
        image: ghcr.io/uengine-oss/react-voice-agent:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: SERVICE_ROLE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: react-voice-agent-service
  labels:
    app: react-voice-agent
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: react-voice-agent
---
apiVersion: v1
kind: Service
metadata:
  name: react-voice-agent-service-prod
  labels:
    app: react-voice-agent-prod
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: react-voice-agent-prod
